# Generated by Django 4.1.6 on 2023-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="price", field=models.IntegerField(),
        ),
    ]
