# Generated by Django 4.1.6 on 2023-12-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
