# Generated by Django 4.1.6 on 2023-12-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
