# Generated by Django 4.1.6 on 2023-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Availability",
            field=models.CharField(
                choices=[("Tersedia", "Tersedia"), ("Habis", "Habis")],
                max_length=100,
                null=True,
            ),
        ),
    ]
