# Generated by Django 4.1.6 on 2023-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_product_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="description", field=models.TextField(null=True),
        ),
    ]
